### ISSUE TITLE
Clarify python version status in docs

### ISSUE THREAD

**Issue by maphew** [calpaterson/dircast#3]
Moving on from #1, next bump in road is `AttributeError: 'file' object has no attribute 'buffer'` which appears to be because `stdout.buffer.write(...)` is python 3 specific construct [[ref](http://stackoverflow.com/questions/3038618/how-can-you-print-a-string-using-raw-unicode-escape-encoding-in-python-3)].

This might be the end of the road for trying to get this to work on my 2.7 environment. Either way the docs could be updated to note working version(s) status.

```
>dircast --debug  "8 Fold Path Edmonton 2013"
INFO:dircast.cli:started
INFO:dircast.files:loading 8 Fold Path Edmonton 2013\channel.yml
Traceback (most recent call last):
  File "b:\osgeo\apps\Python27\Scripts\dircast-script.py", line 9, in <module>
    load_entry_point('dircast==0.0', 'console_scripts', 'dircast')()
  File "b:\osgeo\apps\Python27\lib\site-packages\click\core.py", line 609, in __call__
    return self.main(*args, **kwargs)
  File "b:\osgeo\apps\Python27\lib\site-packages\click\core.py", line 589, in main
    rv = self.invoke(ctx)
  File "b:\osgeo\apps\Python27\lib\site-packages\click\core.py", line 781, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "b:\osgeo\apps\Python27\lib\site-packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "d:\code\dircast\dircast\cli.py", line 19, in main
    stdout.buffer.write(
AttributeError: 'file' object has no attribute 'buffer'
```

**Comment by maphew** [comment]
Note added in 81a1392aeba1d3e8641b2740a2ad3fa3e6558cc7.

I can't address making stdout.buffer work in 2.7, it's over my head.
